#!/bin/bash

set -x
myVar=5

# switch construct
# to match a case

case $myVar in
    1)
	echo 1
    ;;
    2)
	echo 2
    ;;
    3)
	echo 3
    ;;
    4)
	echo 4
    ;;
    5)
	echo 5
    ;;
    6)
	echo 6
    ;;
    7)
	echo 7
    ;;
    8)
	echo 8
    ;;
    9)
	echo 9
    ;;
    10)
	echo 10
    ;;
esac
